version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
          name: Test
          command: |
            gradle test
      - store_test_results:
          path: build/test-results
  jarjar:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
          name: jar
          command:
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
  dockerize:
    machine: true
    steps:
      - checkout
      - run: docker login -u $USER_NAME -p $PASSWORD
      - run: docker build -t $USER_NAME/app:$CIRCLE_SHA1 Docker/
      - run: docker push $USER_NAME/app:$CIRCLE_SHA1


workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - jarjar:
          requires:
            - test
      - dockerize:
          requires:
            - test
            - jarjar
 